import React, { useState } from 'react';
import Image from 'next/image';
import core1 from "../assets/core1.jpg";
import ScrollableTabs from './ScrollTab'
import ItemsList from '../items/ItemsList';
import GlassmorphismCards from './Cards';
import Head from 'next/head';

const ProfilePage = () => {
    const walletAddress = '0x1234567890abcdef'; // Replace with your actual wallet address

    const handleCopy = () => {
        // Logic for copying the wallet address
        console.log('Copied wallet address');
    };

    const handleShare = () => {
        // Logic for sharing the wallet address
        console.log('Shared wallet address');
    };

    const handleDownload = () => {
        // Logic for downloading the wallet address
        console.log('Downloaded wallet address');
    };

    const [activeTab, setActiveTab] = useState('Tab 1');
    const tabs = ['On Sales (24)', 'Collectibles (23)', 'Favorited (9)', 'Owned (10)', 'Activity (0)'];

    const handleTabChange = (tab) => {
        setActiveTab(tab);
    };

    return (
        <>
        <Head>
        <title>My Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
        <div className="mt-20 flex flex-col items-center">
            <Image
                src={core1} // Replace with your actual profile picture URL
                alt="Profile Picture"
                className="mx-auto mt-8 rounded-full w-32 h-32 lg:w-48 lg:h-48"
            />
            <div className="mt-4 text-center">

                <p className="text-white">{walletAddress.substr(0, 8)}...</p>
            </div>
            <div className="flex mt-4">
                <div className="bg-transparent border-white border mx-2 rounded-2xl flex space-x-2">
                    <button
                        onClick={handleCopy}
                        className="flex items-center justify-center px-2 py-2 text-white bg-blue-500 rounded-md hover:bg-blue-600"
                    >
                        <svg
                            width="24"
                            height="24"
                            viewBox="0 0 24 24"
                            fill="none"
                            xmlns="http://www.w3.org/2000/svg"
                        >
                            <path
                                d="M15.75 15.75H20.25V3.75H8.25V8.25"
                                stroke="#BFBFC0"
                                strokeWidth="2"
                                strokeLinecap="round"
                                strokeLinejoin="round"
                            />
                            <path
                                d="M15.75 8.25H3.75V20.25H15.75V8.25Z"
                                stroke="#BFBFC0"
                                strokeWidth="2"
                                strokeLinecap="round"
                                strokeLinejoin="round"
                            />
                        </svg>
                    </button>
                </div>
                <div className="bg-transparent border-white border mx-2 rounded-2xl flex space-x-4">
                    <button
                        onClick={handleShare}
                        className="flex items-center justify-center px-2 py-2 text-white bg-green-500 rounded-md hover:bg-green-600"
                    >
                        <svg
                            width="24"
                            height="24"
                            viewBox="0 0 24 24"
                            fill="none"
                            xmlns="http://www.w3.org/2000/svg"
                        >
                            <g id="Icons/share_24px">
                                <path
                                    id="icon"
                                    fillRule="evenodd"
                                    clipRule="evenodd"
                                    d="M15.97 16.81C16.5 16.31 17.21 16 18 16C19.66 16 21 17.34 21 19C21 20.66 19.66 22 18 22C16.34 22 15 20.66 15 19C15 18.76 15.04 18.53 15.09 18.31L8.04 14.19C7.5 14.69 6.79 15 6 15C4.34 15 3 13.66 3 12C3 10.34 4.34 9 6 9C6.79 9 7.5 9.31 8.04 9.81L15.09 5.7C15.04 5.48 15 5.24 15 5C15 3.34 16.34 2 18 2C19.66 2 21 3.34 21 5C21 6.66 19.66 8 18 8C17.21 8 16.49 7.69 15.96 7.19L8.91 11.3C8.96 11.53 9 11.76 9 12C9 12.24 8.96 12.47 8.91 12.7L15.97 16.81ZM19 5C19 4.45 18.55 4 18 4C17.45 4 17 4.45 17 5C17 5.55 17.45 6 18 6C18.55 6 19 5.55 19 5ZM6 13C5.45 13 5 12.55 5 12C5 11.45 5.45 11 6 11C6.55 11 7 11.45 7 12C7 12.55 6.55 13 6 13ZM17 19C17 19.55 17.45 20 18 20C18.55 20 19 19.55 19 19C19 18.45 18.55 18 18 18C17.45 18 17 18.45 17 19Z"
                                    fill="#BFBFC0"
                                />
                            </g>
                        </svg>
                    </button>
                </div>
                <div className="bg-transparent border-white border mx-2 rounded-2xl flex space-x-2">
                    <button
                        onClick={handleDownload}
                        className="flex items-center justify-center px-2 py-2 text-white bg-purple-500 rounded-md hover:bg-purple-600"
                    >
                        <svg
                            width="24"
                            height="24"
                            viewBox="0 0 24 24"
                            fill="none"
                            xmlns="http://www.w3.org/2000/svg"
                        >
                            <g id="Icons/file_download">
                                <path
                                    id="icon"
                                    d="M18 15V18H6V15H4V18C4 19.1 4.9 20 6 20H18C19.1 20 20 19.1 20 18V15H18ZM17 11L15.59 9.59L13 12.17V4H11V12.17L8.41 9.59L7 11L12 16L17 11Z"
                                    fill="#BFBFC0"
                                />
                            </g>
                        </svg>
                    </button>
                </div>
            </div>
            <GlassmorphismCards />
            <ScrollableTabs tabs={tabs} activeTab={activeTab} onTabChange={handleTabChange} />
            <ItemsList />
        </div>
        </>
    );
};

export default ProfilePage;
